executable            = TEMPL_TASKDIR/conf/run.sh
input                 = TEMPL_TASKDIR/conf/params.sh
arguments             = $(ClusterID) $(ProcId)
output                = TEMPL_TASKDIR/logs/job.$(ClusterId).$(ProcId).out
error                 = TEMPL_TASKDIR/logs/job.$(ClusterId).$(ProcId).err
log                   = TEMPL_TASKDIR/logs/condor.$(ClusterId).log
+JobFlavour           = "TEMPL_JOBFLAVOR"

RequestCpus = TEMPL_NCPU
#MY.WantOS = "el8"
transfer_input_files  = TEMPL_TASKDIR/copy_files.sh,TEMPL_TASKDIR/conf/params.sh,TEMPL_TASKBASEDIR/sandbox.tgz,TEMPL_TASKBASEDIR/cmssw_setup.sh
# +PreCmd               = "cmssw_setup.sh"
+PostCmd              = "copy_files.sh"
+PostArguments              = "$(ClusterID) $(ProcId)"
+AccountingGroup = "group_u_CMST3.all"

transfer_output_files   = ""

# manifest = true

queue TEMPL_NJOBS
